### ISSUE TITLE
add units and raw values for tx, block field values

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/jade-explorer#132]
![Screenshot_20191029_081602](https://user-images.githubusercontent.com/45600330/67770505-8514a480-fa24-11e9-94d8-6ebb43ec1c71.png)

**Is your feature request related to a problem? Please describe.**
Without a description of units for field values (eg. `Value`, `Gas`), I'm not sure how to interpret values I see.

**Describe the solution you'd like**
I'd like all scalar (at least Ether-representing) values shown to also state the units they're measuring, eg. `Wei`, `MWei`, `Eth`... etc.

**Describe alternatives you've considered**
Fancy: Add a dropdown per field or per page to let user select desired units. 
Bonus Fancy: Show raw (undecoded) values, ie hex, also.

**Comment by meowsbits** [comment]
`View Raw` is awesome - but I still want units! :joy_cat:

**Comment by shanejonas** [comment]
let’s get another issue going for displaying units
