### ISSUE TITLE
Custom ethereum RPC is broken

### ISSUE THREAD

**Issue by adamcavendish** [etclabscore/jade-explorer#156]
I'm trying to run jade for a custom eth rpc url and found it not working.

I tried to:

```
# one shell
REACT_APP_ETH_RPC_URL=http://111.112.113.114:2345/my-eth npm run service-runner
# another shell
REACT_APP_ETH_RPC_URL=http://111.112.113.114:2345/my-eth npm start
```

It starts but never stops on loading. Am I doing the right process?

**Comment by shanejonas** [comment]
Hi @adamcavendish, thanks for filing this bug.

I am able to reproduce. Will tag this as bug and get it working.

In the meantime you can ovverride this via the url: 

`http://explorer.jade.builders/?rpcUrl=<url>`

`http://explorer.jade.builders/?rpcUrl=http://111.112.113.114:2345/my-eth`

or localhost if you are running it locally.
