### ISSUE TITLE
Docker Container for Easy Instantiation

### ISSUE THREAD

**Issue by YazzyYaz** [etclabscore/jade-explorer#55]
**Is your feature request related to a problem? Please describe.**
Dockerizing the explorer will enable turn-key instantiation by developers regardless of the environment they're in

**Describe the solution you'd like**
A Dockerfile I can set up with my custom RPC URL. An example below I've been working on.
```
FROM node:10

COPY package*.json ./

WORKDIR /usr/src/app

RUN npm install static && static -d build

COPY . .

EXPOSE 3000

ENV REACT_APP_ETH_RPC_URL https://www.ethercluster.com/etc

RUN ls

CMD ["npm", "start"]
```

**Describe alternatives you've considered**
Running it locally but it's best to containerize the app in one Dockerfile

**Comment by shanejonas** [comment]
Dockerfile landed here: https://github.com/etclabscore/jade-explorer/blob/master/Dockerfile

but need to set up semantic release to deploy to docker hub registry
